{-
   Swagger Petstore

   This is a sample server Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.

   OpenAPI Version: 3.0.1
   Swagger Petstore API version: 1.0.5
   Contact: apiteam@swagger.io
   Generated by OpenAPI Generator (https://openapi-generator.tech)
-}

{-|
Module : PetStore.Logging
Logging functions
-}
{-# LANGUAGE CPP #-}

#ifdef USE_KATIP

module PetStore.Logging
  ( module PetStore.LoggingKatip
  ) where

import PetStore.LoggingKatip

#else

module PetStore.Logging
  ( module PetStore.LoggingMonadLogger
  ) where

import PetStore.LoggingMonadLogger

#endif
