{-
   Vikunja API

   # Pagination Every endpoint capable of pagination will return two headers: * `x-pagination-total-pages`: The total number of available pages for this request * `x-pagination-result-count`: The number of items returned for this request. # Rights All endpoints which return a single item (project, task, etc.) - no array - will also return a `x-max-right` header with the max right the user has on this item as an int where `0` is `Read Only`, `1` is `Read & Write` and `2` is `Admin`. This can be used to show or hide ui elements based on the rights the user has. # Errors All errors have an error code and a human-readable error message in addition to the http status code. You should always check for the status code in the response, not only the http status code. Due to limitations in the swagger library we're using for this document, only one error per http status code is documented here. Make sure to check the [error docs](https://vikunja.io/docs/errors/) in Vikunja's documentation for a full list of available error codes. # Authorization **JWT-Auth:** Main authorization method, used for most of the requests. Needs `Authorization: Bearer <jwt-token>`-header to authenticate successfully.  **API Token:** You can create scoped API tokens for your user and use the token to make authenticated requests in the context of that user. The token must be provided via an `Authorization: Bearer <token>` header, similar to jwt auth. See the documentation for the `api` group to manage token creation and revocation.  **BasicAuth:** Only used when requesting tasks via CalDAV. <!-- ReDoc-Inject: <security-definitions> -->

   OpenAPI Version: 3.0.1
   Vikunja API API version: 0.24.6
   Contact: hello@vikunja.io
   Generated by OpenAPI Generator (https://openapi-generator.tech)
-}

{-|
Module : Vikunja.API.Subscriptions
-}

{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE MonoLocalBinds #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing -fno-warn-unused-binds -fno-warn-unused-imports #-}

module Vikunja.API.Subscriptions where

import Vikunja.Core
import Vikunja.MimeTypes
import Vikunja.Model as M

import qualified Data.Aeson as A
import qualified Data.ByteString as B
import qualified Data.ByteString.Lazy as BL
import qualified Data.Data as P (Typeable, TypeRep, typeOf, typeRep)
import qualified Data.Foldable as P
import qualified Data.Map as Map
import qualified Data.Maybe as P
import qualified Data.Proxy as P (Proxy(..))
import qualified Data.Set as Set
import qualified Data.String as P
import qualified Data.Text as T
import qualified Data.Text.Encoding as T
import qualified Data.Text.Lazy as TL
import qualified Data.Text.Lazy.Encoding as TL
import qualified Data.Time as TI
import qualified Network.HTTP.Client.MultipartFormData as NH
import qualified Network.HTTP.Media as ME
import qualified Network.HTTP.Types as NH
import qualified Web.FormUrlEncoded as WH
import qualified Web.HttpApiData as WH

import Data.Text (Text)
import GHC.Base ((<|>))

import Prelude ((==),(/=),($), (.),(<$>),(<*>),(>>=),Maybe(..),Bool(..),Char,Double,FilePath,Float,Int,Integer,String,fmap,undefined,mempty,maybe,pure,Monad,Applicative,Functor)
import qualified Prelude as P

-- * Operations


-- ** Subscriptions

-- *** notificationsGet

-- | @GET \/notifications@
-- 
-- Get all notifications for the current user
-- 
-- Returns an array with all notifications for the current user.
-- 
-- AuthMethod: 'AuthApiKeyJWTKeyAuth'
-- 
notificationsGet
  :: VikunjaRequest NotificationsGet MimeNoContent [NotificationsDatabaseNotification] MimeJSON
notificationsGet =
  _mkRequest "GET" ["/notifications"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthApiKeyJWTKeyAuth)

data NotificationsGet  

-- | /Optional Param/ "page" - The page number. Used for pagination. If not provided, the first page of results is returned.
instance HasOptionalParam NotificationsGet Page where
  applyOptionalParam req (Page xs) =
    req `addQuery` toQuery ("page", Just xs)

-- | /Optional Param/ "per_page" - The maximum number of items per page. Note this parameter is limited by the configured maximum of items per page.
instance HasOptionalParam NotificationsGet PerPage where
  applyOptionalParam req (PerPage xs) =
    req `addQuery` toQuery ("per_page", Just xs)
-- | @application/json@
instance Produces NotificationsGet MimeJSON


-- *** notificationsIdPost

-- | @POST \/notifications\/{id}@
-- 
-- Mark a notification as (un-)read
-- 
-- Marks a notification as either read or unread. A user can only mark their own notifications as read.
-- 
-- AuthMethod: 'AuthApiKeyJWTKeyAuth'
-- 
notificationsIdPost
  :: Id -- ^ "id" -  Notification ID
  -> VikunjaRequest NotificationsIdPost MimeNoContent ModelsDatabaseNotifications MimeJSON
notificationsIdPost (Id id) =
  _mkRequest "POST" ["/notifications/",toPath id]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthApiKeyJWTKeyAuth)

data NotificationsIdPost  
-- | @application/json@
instance Produces NotificationsIdPost MimeJSON


-- *** subscriptionsEntityEntityIDDelete

-- | @DELETE \/subscriptions\/{entity}\/{entityID}@
-- 
-- Unsubscribe the current user from an entity.
-- 
-- Unsubscribes the current user to an entity.
-- 
-- AuthMethod: 'AuthApiKeyJWTKeyAuth'
-- 
subscriptionsEntityEntityIDDelete
  :: Entity -- ^ "entity" -  The entity the user subscribed to. Can be either `project` or `task`.
  -> EntityId -- ^ "entityId" -  The numeric id of the subscribed entity to.
  -> VikunjaRequest SubscriptionsEntityEntityIDDelete MimeNoContent ModelsSubscription MimeJSON
subscriptionsEntityEntityIDDelete (Entity entity) (EntityId entityId) =
  _mkRequest "DELETE" ["/subscriptions/",toPath entity,"/",toPath entityId]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthApiKeyJWTKeyAuth)

data SubscriptionsEntityEntityIDDelete  
-- | @application/json@
instance Produces SubscriptionsEntityEntityIDDelete MimeJSON


-- *** subscriptionsEntityEntityIDPut

-- | @PUT \/subscriptions\/{entity}\/{entityID}@
-- 
-- Subscribes the current user to an entity.
-- 
-- Subscribes the current user to an entity.
-- 
-- AuthMethod: 'AuthApiKeyJWTKeyAuth'
-- 
subscriptionsEntityEntityIDPut
  :: Entity -- ^ "entity" -  The entity the user subscribes to. Can be either `project` or `task`.
  -> EntityId -- ^ "entityId" -  The numeric id of the entity to subscribe to.
  -> VikunjaRequest SubscriptionsEntityEntityIDPut MimeNoContent ModelsSubscription MimeJSON
subscriptionsEntityEntityIDPut (Entity entity) (EntityId entityId) =
  _mkRequest "PUT" ["/subscriptions/",toPath entity,"/",toPath entityId]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthApiKeyJWTKeyAuth)

data SubscriptionsEntityEntityIDPut  
-- | @application/json@
instance Produces SubscriptionsEntityEntityIDPut MimeJSON

